/** @type {import('tailwindcss').Config} */
import tailwindDynamicHandler from './lib/tailwindPlugin.js';

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Add color classes that might be generated by AI
    {
      pattern: /^(bg|text|border)-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)$/,
      variants: ['hover', 'focus', 'active'],
    },
    // Add sizing, spacing, and other common utility classes
    {
      pattern: /^(p|px|py|pt|pr|pb|pl|m|mx|my|mt|mr|mb|ml)-(0|0.5|1|1.5|2|2.5|3|3.5|4|5|6|8|10|12|16|20|24|32|40|48|56|64)$/,
    },
    {
      pattern: /^(w|h)-(1|2|3|4|5|6|8|10|12|16|20|24|32|40|48|56|64|auto|full|screen)$/,
    },
    {
      pattern: /^(rounded|rounded-t|rounded-r|rounded-b|rounded-l|rounded-tl|rounded-tr|rounded-br|rounded-bl)(-none|-sm|-md|-lg|-xl|-2xl|-3xl|-full)?$/,
    },
    {
      pattern: /^(shadow|shadow-sm|shadow-md|shadow-lg|shadow-xl|shadow-2xl|shadow-inner|shadow-none)$/,
    },
    {
      pattern: /^(flex|grid|flex-row|flex-col|items-|justify-).*$/,
    },
    {
      pattern: /^(font|text)-.+$/,
    },
    {
      pattern: /^(border|divide)-.+$/,
    },
    // Transitions and animations
    {
      pattern: /^(transform|transition|animate)-.+$/,
    },
  ],
  theme: {
    extend: {
      colors: {
        // You can add custom colors here if needed
      },
      animation: {
        // You can add custom animations here if needed
      },
    },
  },
  plugins: [
    tailwindDynamicHandler(),
  ],
}